---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config: "cleancode,codesize,design,unusedcode"
    checks:
      Controversial/CamelCaseParameterName:
        enabled: false
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc"
      standard: "Drupal"
ratings:
  paths:
  - "**.inc"
  - "**.module"
  - "**.php"
exclude_paths: []
