<?php

/**
 * Migrate langcode to field_type_language_code.
 */
function search_api_solr_multilingual_update_8002() {
  foreach (search_api_solr_multilingual_update_helper_get_backend_configs() as $server_name => $backend_config) {
    $backend_config['field_type_language_code'] = $backend_config['langcode'];
    $backend_config['langcode'] = 'en';
    search_api_solr_multilingual_update_helper_save_backend_config($server_name, $backend_config);
  }
}

/**
 * Add default domain settings to existing solr field types and backends.
 */
function search_api_solr_multilingual_update_8003() {
  foreach (search_api_solr_multilingual_update_helper_get_field_type_configs() as $field_type_name => $field_type_config) {
    $field_type_config['domains'] = [];
    search_api_solr_multilingual_update_helper_save_field_type_config($field_type_name, $field_type_config);
  }
  foreach (search_api_solr_multilingual_update_helper_get_backend_configs() as $server_name => $backend_config) {
    $backend_config['sasm_domain'] = 'generic';
    search_api_solr_multilingual_update_helper_save_backend_config($server_name, $backend_config);
  }
}

/**
 * Add search page independent language setting to existing solr backends.
 */
function search_api_solr_multilingual_update_8004() {
  foreach (search_api_solr_multilingual_update_helper_get_backend_configs() as $server_name => $backend_config) {
    $backend_config['sasm_search_page_include_language_independent'] = FALSE;
    search_api_solr_multilingual_update_helper_save_backend_config($server_name, $backend_config);
  }
}
