<?php

/**
 * @file
 * Contains search_api_solr_multilingual.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function search_api_solr_multilingual_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the search_api_solr_multilingual module.
    case 'help.page.search_api_solr_multilingual':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Search API Multilingual Solr Search.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function search_api_solr_multilingual_theme() {
  $theme = [];

  return $theme;
}
