<?php
// $Id$

/**
 * @file
 *
 * @see apachesolr.module
 *
 * @author Markus Kalkbrenner (mkalkbrenner) | Cocomore AG
 *   @see http://drupal.org/user/124705
 *   @see http://drupal.cocomore.com
 */


/**
 * Implements hook_menu().
 */
function apachesolr_multilingual_advanced_solr_menu() {
  $items = array();

  $items['admin/config/search/apachesolr/advanced'] = array(
    'title' => 'Advanced Solr Settings',
    'weight' => 0,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('apachesolr_multilingual_advanced_solr_form'),
    'file' => 'apachesolr_multilingual_advanced_solr.admin.inc',
    'access arguments'   => array('administer search'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}
